### ISSUE TITLE
Add an admin panel

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solserver#35]
Admin should be able to:
- know the managers software version
- update the managers software version

Access to the page should be secured by password or key.

**Comment by keomabrun** [comment]
@twatteyne, I am worried about how we are going to make the solmanager update remotely. 

For instance, we publish a new release with a new mandatory field into the solmanager configuration. Now when If we don't manually modify the local configuration file after updating to the last release, the solmanager will crash. How can we manage that without adding too much complexity ?

**Comment by twatteyne** [comment]
default value in case the field is not present? Have the solserver inform the solmanager of the new field that needs? Let's please don't overthink this :-)
