### ISSUE TITLE
display the scale

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solserver#41]

**Comment by twatteyne** [comment]
I can't see the changes on https://sol.paris.inria.fr/map/, I assume you haven't updated that? I might be a good idea to display the version of the solserver somewhere on the map. If you agree, can you create an issue?
Thanks

**Comment by keomabrun** [comment]
Maybe it is a cache issue ? Can you clean the browser cache ?

**Comment by twatteyne** [comment]
Yep, cache issue, thanks. But there are very few lines.

**Comment by keomabrun** [comment]
I am using the SOL_TYPE_DUST_NOTIF_HRNEIGHBORS from the last 16min.
There is an ongoing issue about that #46.
