### ISSUE TITLE
Use snapshots instead of HR_NEIGHBORS to draw the map links

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solserver#46]

**Comment by twatteyne** [comment]
Cool. Is this now running at https://sol.paris.inria.fr/grafana/map?

**Comment by keomabrun** [comment]
Now running on the dev solserver:
https://sol.paris.inria.fr/map_dev/map.html

**Comment by keomabrun** [comment]
@twatteyne, default time is UTC, you need to slide to UTC-3 for Argentina.

**Comment by twatteyne** [comment]
OK, but I don't understand why that is. Now is now, regardless of where I am. I expect to see the current state of the PEACH network when going to https://sol.paris.inria.fr/map_dev/map.html. It's not like there is a timegap between here and Agentina.

**Comment by keomabrun** [comment]
Argentina is the future !
I will fix the time conversion indeed.

**Comment by twatteyne** [comment]
:-)
