### ISSUE TITLE
Make the map work for different sites

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solserver#48]

**Comment by keomabrun** [comment]
Not fixed !
Dev version can be accessed by:
https://sol.paris.inria.fr/dev/map/ARG_junin/

However, the javascript try to get the https://sol.paris.inria.fr/api/ resources, which are the master branch version of the solserver.

**Comment by twatteyne** [comment]
Cool. I assume you mean "now" rather than "not"?

I don't see the motes though, but I assume that's somehow normal as we pull data from somewhere else?

**Comment by keomabrun** [comment]
I really mean not... I need more time to fix this.

**Comment by twatteyne** [comment]
Hihi, cool :-)
