### ISSUE TITLE
Default map not showing all the nodes and links

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solserver#56]
![screenshot from 2016-10-14 13-43-17](https://cloud.githubusercontent.com/assets/11633612/19386391/34ff944e-9214-11e6-8e1f-a80a789af491.png)

**Comment by twatteyne** [comment]
Still missing some links at https://sol.paris.inria.fr/map/ARG_junin/, no?

**Comment by keomabrun** [comment]
See develop version:
https://sol.paris.inria.fr/dev/map/ARG_junin/

**Comment by twatteyne** [comment]
awesome!!
